### PR TITLE
Pr issue6

### PR DESCRIPTION
**Pull request by biancode**
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes

#6 fix

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [x] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [x] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by biancode** [comment]
I hope the adding LTS to travis and new docs are OK for you.

**Comment by dceejay** [comment]
much cleaner - thanks !

**Comment by biancode** [comment]
The README and node-red-amdin.js changes are there to give the user a consistent documentiation of the commands.

**Comment by biancode** [comment]
When could we get this released, please?

**Comment by knolleary** [comment]
My only hesitation (which has only just occurred to me in this context) is we know the npm search index is generally out of date and we've had to stop using it to find nodes. This means you'd get different results to what the palette manager shows or the flow library itself.

We should update the tool to query the flow library, rather then npm. Currently on a snack break mid-family bike ride. I'll add some comments tonight on what would be needed.

**Comment by knolleary** [comment]
I've got the search working in my local dev environment. It's a simple enough fix to switch over to the flow library api.

I will merge this PR to pick up the other doc changes you've made, but then I'll make the updates for the flow library api. Once that's all done, I'll publish a version of the module.

**Comment by knolleary** [comment]
0.1.8 now published to npm

**Pull request merged**
