### PR TITLE
fix for the broken search feature

### PR DESCRIPTION
**Pull request by biancode**
see issue #6 - from my side issue #3 is also done with the PR

### CODE REVIEW

**Comment by biancode** [comment]
Contributor License Agreement signed as biancode

**Comment by knolleary** [comment]
Hi @biancode thanks for this.

Unfortunately we can't accept it without the CLA being signed off. Looking at your commits, they have been done with the email address `k***.l*****@bi**-roy**.de` - but this email address is not associated with your github account.

The quick fix would be to add this email to your github account so it is able to properly identify these commits as coming from you.

**Comment by biancode** [comment]
e-mail add is done

**Comment by knolleary** [comment]
@jsf-clabot I know you're just a bot, but can I kick you to recheck? Or do we need @biancode to close this PR and open a new one...

**Comment by biancode** [comment]
@jsf-clabot please check again with a recheck of my signed Contributor License Agreement and new e-mail

**Comment by knolleary** [comment]
@biancode I don't think the bot is listening to us 😢 

If you could close this PR and open a new one, that would be appreciated.

**Pull request closed without merging**
